### ISSUE TITLE
Advanced NativeAd, AdActivity Leaks

### ISSUE THREAD

**Issue by wanghang199112** [googleads/googleads-mobile-android-examples#111]
![screenshot_2018-02-28-18-10-18-706_webshare_leak](https://user-images.githubusercontent.com/20058915/36785152-e06d0832-1cbc-11e8-8292-9d1cf5e010f4.png)
![screenshot_2018-02-28-18-10-03-728_webshare_leak](https://user-images.githubusercontent.com/20058915/36785172-ea9f0044-1cbc-11e8-8528-08660d0abcf8.png)

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.

In this case, it appears you are suggesting that one of your activities is leaking due to a google ads reference. In your forum post, please include specific details on your setup and steps to reproduce, in order to help us debug the issue more efficiently.

Regards

Sam
