### ISSUE TITLE
i am created new account in Interstitial ads always fails.

### ISSUE THREAD

**Issue by DharmikAndroid** [googleads/googleads-mobile-android-examples#119]
I was trying to Interstitial ads load but every time ads fail with error code 3 and i am using new admob account.
Can you please provide suggestion on this and let me know why it is not load  Interstitial ads.
I am working with android version (3.0.1) in testing ads id working perfect but live ads id not working.
Let me know if i am doing anything wrong and please provide steps.

        InterstitialAd interstitial = new InterstitialAd(context);
        interstitial.setAdUnitId(context.getResources().getString(R.string.interstial_ad_unit_id));
        adRequest adRequest = new AdRequest.Builder().build();
        interstitial.loadAd(adRequest);
        interstitial.setAdListener(new AdListener() {
            public void onAdLoaded()
            {
		interstitial.show();
            }
            @Override
            public void onAdFailedToLoad(int errorCode)
            {
                super.onAdFailedToLoad(errorCode);
            }
            @Override
            public void onAdClosed()
            {
                super.onAdClosed();  
            }
            @Override
            public void onAdOpened() {
                super.onAdOpened();
            }
        });

**Comment by ericleich** [comment]
When you create a new ad unit ID in the AdMob UI, it takes about an hour to start serving. Considering you mentioned you were using a new AdMob account, I'm guessing this is why your ad unit wasn't working yet. Can you check again and see if you get ads back now?

**Comment by DharmikAndroid** [comment]
Hello, i am trying but as it is issue. now i am get error code 0 and ads load fail.

**Comment by stowy** [comment]
hi, since this isn't an issue with a sample app in this repository, can you please create a support request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently. Please ensure you include all relevant information to reproduce the issue - however we do not recommend including your ad unit ID in the public forum post.
