### ISSUE TITLE
Memory Leak in PublisherAdview

### ISSUE THREAD

**Issue by NitinSharma639** [googleads/googleads-mobile-android-examples#126]
Hello Google Ads Team

I found Memory Leaks in Publisher Adview . I have implemented dfp in an Application which is scrolling horizontally using View Pager. 

Please find attached sample app . I am calling destroy function on PublisherAdview but still it is in the memory . Please check screen shot of My Application and Sample App. Test case was performed on J7 pro. 
<img width="501" alt="screen shot 2018-05-24 at 6 59 34 pm" src="https://user-images.githubusercontent.com/1436185/41527096-b927e74a-7303-11e8-82da-2540e99337f3.png">

https://drive.google.com/file/d/1SwVMzEgEY1hYdsRS0qWepT6dgXVQPg6y/view?usp=sharing

**Comment by ericleich** [comment]
Since the sample app is modified in this case, it doesn't sound like it's a direct problem with the samples in this repo, but perhaps the Google Mobile Ads SDK itself or an implementation issue. Either way, the [Google Mobile Ads SDK developer forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) is a better place to get this question answered.
