### ISSUE TITLE
Cannot import into Android Studio...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleads/googleads-mobile-android-examples#16]
This is what I get:

![untitled20150704171051](https://cloud.githubusercontent.com/assets/5357526/8508198/a70678b6-226f-11e5-8435-64ca09dcbd8a.png)

**Comment by RedBrogdon** [comment]
How did you import the projects into Android Studio? Our recommended approach is the use the "Import Project (Eclipse ADT, Gradle, etc.)" option in the splash screen menu and then select the root folder of an individual project. They're not really meant to be opened all at once.

**Comment by AndroidDeveloperLB** [comment]
I've used this menu :
![untitled20150704203851](
https://cloud.githubusercontent.com/assets/5357526/8508876/bd23c492-228c-11e5-80a0-fde35554271a.png
)
And then I entered this:
"https://github.com/googleads/googleads-mobile-android-examples.git"
and chose "next" for each of the steps.
Doing the same via the menu that appears when you close all projects
results in the same issue.
If I could attach here a video, I could have shown you that it indeed
occurs.

Maybe it's an Android-Studio issue?
I have got an error to report when it occurs...
Here's its info:
Android Studio AI-141.2024585
Build #AI-141.2024585, built on June 18, 2015
JRE: 1.8.0_40-b25 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by RedBrogdon** [comment]
Ah, I see. The issue here is that our git repo for the examples contains six individual projects, rather than one large project. It's not meant to be opened from its root directory (as many other repos are). Android Studio thinks that you're asking it to clone the repo and load a new project that can be found in the root directory, which isn't how the source is set up.

If you have git installed on your machine, you can clone the repo from the command line, then import whichever project you'd like to see from there using the "Import Project..." choice in the menu. You can also download the individual projects directly using the [Releases](https://github.com/googleads/googleads-mobile-android-examples/releases) section of our Github repo and import them the same way.

Our instructions for getting the projects up and running could use some more detail. I'll make a note to flesh them out in the next release.

**Comment by AndroidDeveloperLB** [comment]
Can't Android-Studio know that it has multiple samples? Also, as I remember
it can have multiple runnable projects shown on the same screen...
I even remember seeing such repos that have multiple runnable projects...
Why can't it work this way here too?

**Comment by Greatwhite94127** [comment]
android studio, i am

**Comment by Greatwhite94127** [comment]
i change my machine to compatable corrosponding OS/hardware fraud. moble odin, add ons, shapeshift...
