### ISSUE TITLE
How to add meta data value?

### ISSUE THREAD

**Issue by sahujaunpuri** [googleads/googleads-mobile-android-examples#163]
how to add **com.google.android.gms.version" android:value**  programmable ?
becoz I have need to create an extension for the app inventor source code.
there was no option to add 

< meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

 in xml file

**Comment by ericleich** [comment]
Hi there,

Closing this issue since it's unrelated to the sample apps themselves.

You shouldn't need to add this metadata field if you are able to reference `com.google.android.gms:play-services-ads:17.2.0` in your app inventor app, as demonstrated in https://developers.google.com/admob/android/quick-start#example_app-level_buildgradle_excerpt. If you can reference this way, it'll automatically set this google play services version for you. Having said that, app inventor is outside the scope of our support, and I'm not familiar with how you go about adding SDK dependencies in app inventor.
