### ISSUE TITLE
show interstitial ads with asyncTasks ... is it against the policy?

### ISSUE THREAD

**Issue by midou221** [googleads/googleads-mobile-android-examples#313]
I am running an interstitial ad on asyncTasks but a while ago I received a violation of Google policy
but the ad always opens after the loading screen and before the content is displayed
and the frequency once every 10 minutes

this my code:
` @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {

       MobileAds.initialize(this, getString(R.string.admob_app_id));
            mInterstitialAd = new InterstitialAd(this);
            mInterstitialAd.setAdUnitId("ca-app-pub-3940256099942544/8691691433");
            AdRequest request = new AdRequest.Builder().build();
            mInterstitialAd.loadAd(request);

}

 private class MyTask extends AsyncTask<String, Void, String> {

        @Override
        protected void onPreExecute() {
            super.onPreExecute();
        }

        @Override
        protected String doInBackground(String... params) {

        }

        @Override
        protected void onPostExecute(String result) {
            super.onPostExecute(result);

            mInterstitialAd.setAdListener(new AdListener(){

                @Override
                public void onAdLoaded() {
                    super.onAdLoaded();

                    if (mInterstitialAd.isLoaded() && mInterstitialAd != null){
                        mInterstitialAd.show();
                    }

                }

        });
            mInterstitialAd.loadAd(new AdRequest.Builder().build());

    }
`

please some help

**Comment by ericleich** [comment]
@midou221 AsyncTask itself is fine. It's not a great practice to show an interstitial immediately after it's loaded, because you can't control when it'll show and it may be a bad user experience and a [disallowed interstitial implementation](https://support.google.com/admob/answer/6201362).

If you're trying to show an ad when the app launches, you may consider trying out https://developers.google.com/admob/android/app-open-ads instead.

Also, for future AdMob technical questions that are unrelated to the sample apps themselves on GitHub here, please use the dedicated [Google Mobile Ads SDK developer support forum](https://groups.google.com/group/google-admob-ads-sdk).
