### ISSUE TITLE
Not enough space to show ad

### ISSUE THREAD

**Issue by zboing** [googleads/googleads-mobile-android-examples#41]
If nativeexpressrecyclerviewexample is built in android studio on devices **lower than api 21**, the below error occurs in the logcat and the ad is not displayed in the card view:

> Not enough space to show ad. Needs 304x150 dp, but only has 300x0 dp.

**Comment by temrich** [comment]
Hi, thank you for reporting this.

Can you provide the devices and versions of Android that you used when you saw this error in logcat?

**Comment by temrich** [comment]
Hi, we were able to identify the issue and will be pushing an updated version of the Native Express RecyclerView example shortly. The issue was with extra padding that is added to a CardView with pre-Lollipop versions of Android.

In the meantime, you can replace lines 104 - 106 in MainActivity.java (https://github.com/googleads/googleads-mobile-android-examples/blob/master/advanced/NativeExpressRecyclerViewExample/app/src/main/java/com/google/android/gms/example/nativeexpressrecyclerviewexample/MainActivity.java#L104)

with the following:

final CardView cardView = (CardView) findViewById(R.id.ad_card_view);
final int adWidth = cardView.getWidth() - cardView.getPaddingLeft() - cardView.getPaddingRight();
AdSize adSize = new AdSize((int) (adWidth / density), NATIVE_EXPRESS_AD_HEIGHT);

Thanks again for reporting this. We definitely appreciate it!

**Comment by zboing** [comment]
Thanks. It works with the code provided
