### ISSUE TITLE
Request: use caching to minimize loading time

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleads/googleads-mobile-android-examples#48]
According to [this post](https://github.com/googleads/googleads-mobile-android-examples/issues/47) , ads get re-loaded for every new Activity instance, even if the Activity got recreated due to orientation change.

It's a really bad UX to have an ad load itself again and again, for each new Activity and orientation change.

Why not use caching?
Just cache the ad to the RAM (can store using JNI for less strain in Java Heap, if you wish), and re-use it.

Not only that, but you can cache to storage (you can let us choose where to cache, this would be nice), so that in future runs of the app, loading the ad would be nearly instant, and you won't even need to access the Internet every single time.

**Comment by ericleich** [comment]
I'm going to close this issue since it is more of an SDK feature request rather than an update to the examples. A better place to discuss SDK issues is the [developer forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk)

There is currently a proposal to do support getting the same ad back across consecutive Activities, but it is going to need thorough testing. It will be at least a few months out, and I can't provide a specific timeline.

**Comment by AndroidDeveloperLB** [comment]
I did, but I don't know if it helps:
https://groups.google.com/forum/#!topic/google-admob-ads-sdk/-uzO6ocBTGo
