### ISSUE TITLE
Banner Expand issue

### ISSUE THREAD

**Issue by serg94** [googleads/googleads-mobile-android-examples#50]
`mraid.expand()` doesn't dispatch `stateChange` event, and `mraid.getState()` returns default after expand.

**Comment by ericleich** [comment]
Hi serg94,

This is a known issue with the Google Mobile Ads SDK. It won't be fixed for the Google Play services version rolling out right now, but will be fixed in the next major update.

For future issues with the Google Mobile Ads SDK, we recommend asking these questions on our [developer forum](https://groups.google.com/group/google-admob-ads-sdk). If there is an issue with the sample app itself, this is the best place to file it.
