### ISSUE TITLE
RewardedVideoExample doesn't work - Failed to load ad: 0

### ISSUE THREAD

**Issue by pungrue26** [googleads/googleads-mobile-android-examples#53]
I installed the RewardedVideoExample app with

adding 
`AdRequest.Builder().addTestDevice("8AFB9AA9EDB01A3284A022CD8FF7772B")`, 

also replacing
`AD_UNIT_ID` to "ca-app-pub-2459240923576903/6568419277", and
`APP_ID` to "ca-app-pub-2459240923576903~4318446874"

but it just doesn't work. Logcat says 

```
There was a problem getting an ad response. ErrorCode: 0
Failed to load ad: 0
```

but I can't even find what the 0 means in the [reference](https://firebase.google.com/docs/reference/android/com/google/android/gms/ads/reward/RewardedVideoAdListener.html#onRewardedVideoAdFailedToLoad(int)).

Am I missing something?

**Comment by ericleich** [comment]
Hi there,

Couple of things:

1. `addTestDevice` currently doesn't work with rewarded ads. We'll be fixing this within the next week. In the meantime, if testing without `addTestDevice`, please don't click on the ads you see, since you don't want your account flagged for invalid activity. We know this isn't a great solution at the moment and we are working on it.
2. `ca-app-pub-2459240923576903/6568419277` looks like it's actually an interstitial ad unit. Make sure to use your ad unit for rewarded video when requesting rewarded video ads.
3. The error codes are [here](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#ERROR_CODE_INTERNAL_ERROR). The Javadocs can be updated in a future version to make this more clear. Although, "internal error" doesn't give much information, other than its not one of the other codes.

**Comment by pungrue26** [comment]
Hi Eric,

Many thanks for your immediate reply. 

Yes, you are right. Above ad_unit turns out interstitial type rather than rewarded video type. I just made a mistake. 

Also, I thought that I just can download the project & build & run right away, but it seems I need to add network adapters to `lib` directory by myself. I missed this step too.

**Comment by ericleich** [comment]
We are working on getting some test ads set up for rewarded, and expect that by this time next week we will push an updated sample that will run out of the box.
