### ISSUE TITLE
Can't Load Rewarded Ad

### ISSUE THREAD

**Issue by marioacarvalho** [googleads/googleads-mobile-android-examples#61]
Hi,

trying to run your example about Rewarded Ads but it's always failing to load it.

Listener called is `onRewardedVideoAdFailedToLoad` with error code 2.

AppID: `ca-app-pub-9020278073797626~9034536795`
BannerID: `ca-app-pub-9020278073797626/1511269997`

**Comment by ericleich** [comment]
I'm getting ads back with your ad unit. There is a known issue where ads aren't working on emulators right now, but if that was your issue you'd come back with error code 0. Error code 2 is a network issue, which typically means no internet connection on your device, or you have ad blocker or something equivalent which is preventing the ad request from going through.

Since I don't think this is related to the sample, I'm closing this ticket. For general support, please write into our [developer forum](groups.google.com/group/google-admob-ads-sdk).
