### ISSUE TITLE
NativeAdViewHolder的疑问

### ISSUE THREAD

**Issue by mutour** [googleads/googleads-mobile-android-examples#97]
我们现在开始接入11.6.0的sdk，发现里面新增了一个NativeAdViewHolder的类，用来传入自定义的view，但是我们发现在使用这个类展示广告时，无法成功，logcat提示“” Your account must be enabled to use this feature. Talk to your account manager to request this feature for your account.“”，而且在admob后台也没看到有相关权限需要开启。开发者文档和Sample工程中也没有提到该类使用方式。
请问提示该内容是什么原因，该怎么解决，还是该接口不是针对开发者用的？麻烦给予提示，谢谢~

**Comment by RedBrogdon** [comment]
You have a sharp eye!

We sometimes add experimental features to the SDK so that they can be beta tested. `NativeAdViewHolder` is one of those features. It's not meant to be used by our publishers yet, though it may be in the future. If that happens, we'll update our developer guide at https://developers.google.com/admob/android/native-advanced and post on the [Ads Developer Blog](http://googleadsdeveloper.blogspot.com/).

Thanks!
