### ISSUE TITLE
how can I create the unit id of Native Ads Advanced for my app, i foundn't the interface where i can get, please help

### ISSUE THREAD

**Issue by cqswxj2013** [googleads/googleads-mobile-android-examples#98]
now, i follow the next steps, but i can't find the native

1. 访问https://apps.admob.com并登录到您的AdMob帐户。
2. 点击获利标签。
3. 从左侧的所有应用列表中选择您的应用。
4. 点击+新广告单元。
5. 点击原生。

**Comment by stowy** [comment]
Hi, Native Ads Advanced is in limited beta at the moment. If you haven't got access to it, it is because you are not part of the limited beta. If you have an account manager, you can reach out to them about it. Otherwise, we suggest utilizing the [Banner format](https://developers.google.com/admob/android/banner).

Also more generally, these github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.
